Book_Store1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from app import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView 
urlpatterns = [
    path('home/',views.homeview.as_view()),
    path('contact/',views.contactview.as_view()),
    path('insertcontact/',views.insertcontact),
    path('featured/<str:type>/',views.featuredview),
    #path('arrivals/',views.arrivalsview.as_view()),
    path('reviews/',views.reviewsview.as_view()),
    path('about/',views.aboutview.as_view()),
    path('signup/',views.signup),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    
    path('bookdetail/<int:id>',views.bookdetail),
    path('faq/',views.faqview.as_view()),
    path('blog/',views.blogview),
    path('payment/',views.paymentview.as_view()),
    path('privacy/',views.privacyview.as_view()),
    path('terms/',views.termsview.as_view()),
    path('copyright/',views.copyrightview.as_view()),
    path('blogdetail/<int:id>',views.blogdetailview),
    path('Myorder/',views.Myorderview),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]
'''path('english/',views.englishview.as_view()),
    path('punjabi/',views.punjabiview.as_view()),
    path('hindi/',views.hindiview.as_view()),'''

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

app/templates/Myorder.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5"  data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">My</span> Orders </h2>
    </div>
</div>
 
<div class="row p-5">
    <table class="table">
        <tr>
            <th>Sr No</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Order Date</th>
            <th>Payment Status</th>
        </tr>
        {% for c in c %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ c.product }}</td>
            <td>{{ c.price }}</td>
            <td>{{ c.quantity }}</td>
            <td>{{ c.order.updated }}</td>
            <td>{% if c.order.paid == True %}
                PAID
                {% else %}
                NOT PAID
                {% endif %}
            </td>
        </tr>
        
        {% endfor %}
    </table>
</div>

{% endblock %}

app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="p-3">
  <img src="{% static 'images/photo-6.jpg' %}" class="d-block w-100" alt="...">
</div>

<div class="col-md-12 text-center p-5">
  <h2 class="text-uppercase fw-bold display-5"><span class="text-info">About</span> us</h2>
</div>

<div class="row p-5" id="banner" data-aos="fade-down-right">
    <div class="col-md-12" id="subbanner">
        <div class="col-md-12">
            <h2 class="text-info  display-4 fw-bold" data-aos="flip-right">Bookly</h2>
            <h1 class="text-light fs-1 fw-bold">Always dedicated and devoted</h1>
            <p class="text-dark fs-4" data-aos="flip-right"> Bookly is the online platform where you can get more and more 
            books with amazing discounts.</p>
            <p class="text-light fs-4" data-aos="flip-right"> This is the world of books......</p>
        </div>
    </div>
</div>
<div class="p-4">
    <div class=" row p-3 border border-light bg-info text-light">
        <div class="col-md-12 text-center">
            <h5>Bookly is India’s Largest and Cheapest Online Bookstore offering 40+ Million selections.</h5>

                <h5>“I declare after all there is no enjoyment like reading!”</h5>
                <h5>- Bookly, Pride and Prejudice.</h5>
        </div>
    </div>
</div>
<div class="p-4">
    <div class=" row p-3 border border-light bg-info text-light">
        <div class="col-md-12">
            <h5>Dear readers,</h5>

            <h5>We offer a huge collection of books from diverse categories of Fiction, Non-fiction, Biographies, History, Religion, Self-Help, etc. We also offer a collection of Investments and Management, Computers, Engineering, Medical, College and School text reference books.</h5>
                
            <h5>We strive for customer satisfaction by offering a user-friendly search engine, efficient payment options and seamless delivery systems. Apart from all this, we also provide great deals and discounts on our products.</h5>
                
            <h5>All the Publishers, Distributors and Authors around the country are welcome to partner with us and grow the Bookly family. We would like to thank our customers for shopping with us. You can write to us on our e-mail id to share any suggestions or feedback you might have regarding our website or services.</h5>
        </div>
    </div>
</div>


<!-- slider start -->
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/slider-11.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-info">Welcome to Bookly World</h3>
        <p>Get books of your own choice.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/slider-12.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-info">Welcome to Bookly World</h3>
        <p>Buy books on Amazing Discounts.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/slider-13.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="text-info">Welcome to Bookly World</h3>
        <p>A book is a gift you can open again and again.</p>
      </div>
    </div>
    
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>
<!--slider end--> 

{% endblock  %}

app/templates/arrivals.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5" id="featured" data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">New</span> Arivals</h2>
        <p class="text-dark fw-bold bg-info">" If you love books and if you love to read, you probably like nothing better than collecting books. "</p>
    </div>
    
    <div class="row p-5">
    {% for pro in object_list %}
        
        <div class="col-md-4">
            <div class="col-md-12 arivalsdiv">
                <div class="text-center">
                    <img src="/media/{{ pro.photo }}"  />
                </div>
                <div class="p-3 bg-dark text-light">
                    <h4>{{ pro.name }}</h4>
                    <div class="d-flex text-danger">
                        <h2 class="pe-4">&#8377;{{ pro.sellingprice }}</h2>
                        <h4 class="text-decoration-line-through ">&#8377; {{ pro.mrp }}</h4>
                    </div>
                    <button class="btn btn-info text-light fw-bold rounded-5">Add to cart</button>
                </div>
            </div>
        </div>
    
    {% endfor %} 

    </div>

</div>

{% endblock %}

app/templates/base.html
{% load static %}
<html>
  <head>
    <title>Book Shop</title>
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'css/bootstrap-grid.min.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'style1.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'aos-master/dist/aos.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'aos-master/dist/aos.js' %}"></script>
    <script>
    $(document).ready(function(){
      AOS.init();
      });
    </script>
  </head>

  <body>

    <div class="container-fluid p-3">

      <div class="row bg-info p-4 stiky-top" id="header" data-aos="flip-up">
       <div class="col-md-3 ps-5">
          <img src="{% static 'images/logo-2.png' %}" height="50" width="100" />  
        </div>
    <div class="col-md-7 offset-0 ">
      <nav>
        <ul class="nav">
          <li><a href="/home/" class="nav-link">Home</a></li>
          <li><a href="/about/" class="nav-link">About us</a></li>

          <div class="dropdown" >
            <button class="btn dropdown-toggle fw-bold" type=button data-bs-toggle="dropdown" aria-expanded="false" id="btnmenu">Books</button>
            <ul class="dropdown-menu">
              <a href="/featured/English/" class="dropdown-item">English</a>
              <a href="/featured/Punjabi/" class="dropdown-item">Punjabi</a>
              <a href="/featured/Hindi/" class="dropdown-item">Hindi</a>
              <a href="/featured/New Arrival/" class="dropdown-item">New Arrival</a>
              <a href="/featured/Best Seller/" class="dropdown-item">Best Seller</a>
              <a href="/featured/Featured/" class="dropdown-item">Featured</a>
              <a href="/featured/Action/" class="dropdown-item">Action</a>
              <a href="/featured/Adventure/" class="dropdown-item">Adventure</a>
            </ul>
          </div>
           
          <li><a href="/contact/" class="nav-link">Contact us</a></li>
         
          <li><a href="/faq/" class="nav-link">FAQ</a></li>
          <li><a href="/blog/" class="nav-link">Blogs</a></li>
        
          {% if user.is_authenticated %}
            <div class="dropdown" style="z-index:99999999">
              <button class="btn dropdown-toggle fw-bold" type=button data-bs-toggle="dropdown" aria-expanded="false" id="btnmenu">Order History
              </button>
              <ul class="dropdown-menu">
                
                <li><a href="/Myorder/" class="nav-link">My Orders</a></li>
                <li><a class="nav-link"> Hi {{ user.first_name }}</a></li>
                <li><a href="/logout/" class="nav-link">Logout</a></li>
              </ul>
            </div>
            {% else %}          
            {% endif %}
            

        </ul>
      </nav>
    </div>

    <div class="col-md-2 text-center">
      <nav>
        <ul class="nav">
          <div class="icons pt-2">
            <a href="{%url 'cart:cart_detail' %}" class="fas fa-shopping-cart"></a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          </div>

          <div class="dropdown" style="z-index:99999999">
            <button class="btn dropdown-toggle" type=button data-bs-toggle="dropdown" aria-expanded="false" id="btnmenu">
              <i class="fa-solid fa-user-lock" id="login-btn"></i>
            </button>
            <ul class="dropdown-menu">

              {% if user.is_authenticated %}
              <li><a class="nav-link"> Hi {{ user.first_name }}</a></li>
              <li><a href="/logout/" class="nav-link">Logout</a></li>
              {% else %}
              <li><a href="/signup/" class="nav-link">Register</a></li>
              <li><a href="/login/" class="nav-link">Login</a></li>
              {% endif %}

            </ul>
          </div>
        </ul>
      </nav>
    </div>
    </div>

    <!--header end-->


    {% block content %}


    {% endblock %}


    <div class="row" id="footer">
      <div class="col-md-12 text-center" id="subfooter">
      
        <div class="row">
          <div class="col-md-4">
            <img src="{% static 'images/logo-3.jpg' %}" height="70" width="150" />
            <br/>
            <br/>
        
            <p><a href="https://mail.google.com/mail/?view=cm&fs=1&to=bookly111@gmail.com" target="_blank"><i class="fa fa-envelope"></i> bookly111@gmail.com</a></p>
            <p><i class="fa fa-phone"></i> +91 96533 53353</p>
            <p><i class="fa fa-map-marker"></i> Near Bus Stand, Jaito</p>
          </div>
          
        <div class="col-md-3 text-center">
          <h5 class="text-uppercase fw-bold"><span class="text-info">Quick</span> Links</h5>
          <ul class="navbar-nav">
            <li><a href="/home/" class="nav-link">Home</a></li>
            <li><a href="/about/" class="nav-link">About us</a></li>
            
            <li><a href="/contact/"class="nav-link">Contact us</a></li>
            <!--<li><a href="/reviews/"class="nav-link">Reviews</a></li> -->
          </ul>
        </div>

        <div class="col-md-2">
          <h5 class="text-uppercase fw-bold"><span class="text-info">Need</span> Help</h5>
          <ul class="navbar-nav">
            <li><a href="/payment/" class="nav-link">Payment</a></li>
            <!-- <li><a href="//"class="nav-link">Return</a></li> -->
            <li><a href="/faq/"class="nav-link">FAQ</a></li>
            <li><a href="/blog/"class="nav-link">Blogs</a></li>
          </ul>
        </div>

        <div class="col-md-3">
          <h5 class="text-uppercase fw-bold"><span class="text-info">Policies</span></h5>
          <ul class="navbar-nav">
            <li><a href="/privacy/" class="nav-link">Privacy Policies</a></li>
            <li><a href="/terms/" class="nav-link">Terms of Use</a></li>
            <li><a href="/copyright/"class="nav-link">Copyright Policy</a></li>
            <li><a href="//"class="nav-link"></a></li>
          
          </ul>
        </div>

        <div class="col-md-12 border border-light mt-5"></div>
        <div class="col-md-12 p-3 text-center">
          <p> Designed By <span class="text-info">Bookly</span> | All Rights Reserved!</p>
        </div>
      
        </div>
      
      </div>
    </div>
        <!--footer end-->
      

    </div>

  </body>
</html>

app/templates/blog.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}


<div class="row p-5" id="blog" data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">Latest</span> Blogs </h2>
    </div>
</div>

<div class="row">
    {% for pro in blg %}
    <div id="box" class="col-md-6 p-3 blogs">
        <a href="/blogdetail/{{ pro.id }}">
        <h3>{{ pro.name }}</h3>
        <img src="/media/{{ pro.photo }}" width="100%"  />
        <p>{{ pro.postby }} ({{ pro.poston }})</p>
        </a>
    </div>
    {% endfor %}
</div>

<!--
<div class="row border border-dark p-5">
    {% for pro in blg %}
        
        <div class="col-md-4 p-5">
            <div class="col-md-12" id="blog">
                <div class="text-center">
                    <img src="/media/{{ pro.photo }}" hieght="200" width="200"  />
                </div> 
                
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{ pro.name }}</h4>
            
            <p>{{ pro.description }}</p>
        </div>
    {% endfor %} -->
  

{% endblock %}

app/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="p-2">
<div class="row banner text-center text-light p-3">
<div class="col-md-12">
<h1 class="fw-bold">CONTACT</h1>
<!-- <div class="col-md-4 offset-5">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb p-5">
      <li class="breadcrumb-item"><a href="/home/">Home</a></li>
      <li class="breadcrumb-item active text-light" aria-current="page">Contact</li>
    </ol>
</nav>
</div> -->
</div>
</div>
<div class="row p-3">
<div class="col-md-5 p-5 bg-info text-light">
<h1 class="text-info text-center bg-light"> Request a Call Back</h1>
<p class="text-center">Bookly is the best online platform to purchasing books.</p>

<h3>Address</h3>
<p><i class="fa fa-map-marker"></i> Near Bus Stand, Jaito</p>

<h3>Email</h3>
<p><i class="fa fa-envelope"></i> bookly@gmail.com</p>

<h3>Phone</h3>
<p><i class="fa fa-phone"></i> +91 96523 42324</p>
</div>
    <div class="col-md-7 p-5">
        <form action="/insertcontact/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <input type="text" name="firstname" class="form-control" placeholder="First name" />
                </div>
                <div class="col-md-6">
                    <input type="text" name="lastname" class="form-control" placeholder="Last name" />
                </div>
                <div class="col-md-6 mb-3">
                    <input type="tel" name="phone" class="form-control" placeholder="Phone number" />
                </div>
                <div class="col-md-6">
                    <input type="text" name="subject" class="form-control" placeholder="Subject" />
                </div>
                <div class="col-md-12 mb-3">
                    <input type="email" name="email" class="form-control" placeholder="Email address" />
                </div>
                <div class="col-md-12 mb-3">
                    <textarea name="message" class="form-control" placeholder="Leave your Message"></textarea>
                </div>
                <div class="col-md-12 mb-3">
                    <label>Upload Picture</label>
                    <input type="file" class="form-control" name="pic"/>
                </div>
                <div class="col-md-6 mb-3 p-3">
                    <button class="btn btn-info text-light fw-bold">Submit Now</button>
                </div>
            </div>
        </form>
    </div>

</div>
</div>

{% endblock %}

app/templates/copyright.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}




<div class="p-5">       
    <div class="col-md-12 p-3">
        <h2>Copyrights Policy</h2>
        <p>Copyright in this Website belongs to SR Ecommerce Factory Private Limited ("Bookly"). Bookly also uses contents of their vendors and third parties as well who might not be the original owners of copyright therein. The users should assume that standard copyright protection applies to all materials and contents displayed on the Website. Any redistribution, modification or reproduction of part or all of the contents featured in the Website in any form is prohibited. You may display, print, or download the contents to a local hard disk extracts for your personal, non-commercial use, but only if you acknowledge the Website as the source of the material. You are not permitted, except with the express written consent of Bookswagon, to distribute or commercially exploit the contents on this Website. You are also prohibited from transmitting the contents or storing it in any other Website or in other form of electronic retrieval system.</p>

    </div>
    <div class="p-3"> 
        <h4>1. Intellectual Property Rights Policy</h4>  
        <p>www.Bookly.com ("Website" or "Bookly") contains the trademark "Bookly", creations with the trademark "Bookly", other trademarks, logos, trade name, service marks and other marks (collectively "Marks") which are the intellectual property of SR Ecommerce Factory Private Limited ("Bookly"). You agree not to challenge the use, registration or application to register the Marks, anywhere in the world, and that You will not harm, misuse, or bring into disrepute any of the Marks. The goodwill derived from using the Marks or any part thereof, shall inure exclusively to the benefit of Bookly or its vendors or the third party that may own the Marks. All Marks, domain name, trade dress including the "look and feel" of the Website, its text, graphics, button icons, interfaces, etc., and the arrangements thereof, is the property of Bookly or its vendors or the third party, as the case may be, unless otherwise indicated. All the contents are protected under copyright, trademark and other applicable intellectual property laws and may not be used by You, except as permitted by Bookly, its vendors or the concerned third party.</p>

        <h4>2. Notification of copyright infringement - [Take Down Notice]</h4>
        <p>If you are the owner of copyright in any content available on www.Bookly.com ("Website" or "Bookly") and uploaded without your consent, or you believe that your content has been copied in any way that constitutes infringement, please provide the following information to the Company Secretary/Manager Legal of Bookly:</p>
        <p>A statement specifying that you have found specific content on the Website e.g., video/ audio/text/graphic content, which you believe infringes your copyright;
        </p>
        <p>The title and description of the content, as available on the Website, and the full URL of the web page where the content is available;</p>
        <p>Description of the content/work, the copyright - which belongs to you, and which you believe has been infringed. In case this information is available on the internet, please send Bookly a link to the same;</p>
        <p>The country in which your copyright applies;</p>
        <p>An explanation on how the content available on the Website infringes your copyright (e.g. in case of any audio content, the musical works or the sound recordings are a copy of your original works, etc.);</p>
        <p>Your contact information so that Bookly can get in touch with you (e-mail address is preferred);</p>
        <p>Your contact information which Bookly can pass on to the submitter of the concerned content, so that he/she can get in touch with you to resolve your complaint directly (e-mail address is preferred);</p>
        <p>A statement by you that you have a good faith belief that the disputed use of the copyrighted work is not authorized by the copyright owner (or by a third party who is legally entitled to do so on behalf of the copyright owner, such as his agent) and is not otherwise permitted by law; and</p>
        <p>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</p>
    </div>       
</div>

{% endblock %}

app/templates/english.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5" id="featured" data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">English</span> Books</h2>
        
    </div>
    
    <div class="row p-5">
    {% for pro in object_list %}
        
        <div class="col-md-4">
            <div class="col-md-12 engdiv">
                <div class="text-center">
                    <img src="/media/{{ pro.photo }}"  />
                </div>
                <div class="p-3 bg-dark text-light">
                    <h4>{{ pro.name }}</h4>
                    <div class="d-flex text-danger">
                        <h2 class="pe-4">&#8377;{{ pro.sellingprice }}</h2>
                        <h4 class="text-decoration-line-through ">&#8377; {{ pro.mrp }}</h4>
                    </div>
                    <button class="btn btn-info text-light fw-bold rounded-5">Add to cart</button>
                </div>
            </div>
        </div>
    
    {% endfor %} 

    </div>

</div>

{% endblock %}

app/templates/faq.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5" id="faq" >
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">FAQ's</span> </h2>
    </div>
</div>

<div class="row">
   
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="accordion accordion-flush mt-5 " id="accordionFlushExample">
                
                {% for pro in object_list %}

                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-heading{{ pro.id }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" 
                            data-bs-target="#flush-collapse{{ pro.id }}" aria-expanded="false" aria-controls="flush-collapse{{ pro.id }}">
                            <i class="fa fa-arrow-right me-3"></i>
                            {{ pro.question }}
                        </button>
                        </h2>
                        <div id="flush-collapse{{ pro.id }}" class="accordion-collapse collapse"
                            aria-labelledby="flush-heading{{ pro.id }}" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">{{ pro.answer }}</div>
                        </div>
                    </div>
        
                    <!-- <div class="col-md-12 border border-dark p-1">
                        <div class="col-md-12 p-2">
                
                            <div>
                                <h4>{{ pro.question }}</h4>
                                <h5>{{ pro.answer }}</h5>
                            </div>
                        </div>
                    </div> -->
                
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row pt-5 pb-5">
        <span class="border-bottom"></span>
    </div>
</div> 



{% endblock %}

app/templates/hindi.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5" id="featured" data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">Hindi</span> Books</h2>
        
    </div>
    
    <div class="row p-5">
    {% for pro in object_list %}
        
        <div class="col-md-4">
            <div class="col-md-12 hindidiv">
                <div class="text-center">
                    <img src="/media/{{ pro.photo }}"  />
                </div>
                <div class="p-3 bg-dark text-light">
                    <h4>{{ pro.name }}</h4>
                    <div class="d-flex text-danger">
                        <h2 class="pe-4">&#8377;{{ pro.sellingprice }}</h2>
                        <h4 class="text-decoration-line-through ">&#8377; {{ pro.mrp }}</h4>
                    </div>
                    <button class="btn btn-info text-light fw-bold rounded-5">Add to cart</button>
                </div>
            </div>
        </div>
    
    {% endfor %} 

    </div>

</div>

{% endblock %}

app/templates/payment.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}




<div class="p-5">       
    <div class="col-md-12 p-3">
        <h2>Payments</h2>
    </div>
    <div class="p-3"> 
        <h4>Razorpay Payments:</h4>  
        <p>We accept all Razorpay payments, both Indian and International. Click on the "Add to cart" button and click on "Pay Now" button.  We also accept general mode of payments.</p>
        <h5 class="fw-bold">We also accept general mode of payments.</h5>
    </div>       
</div>

{% endblock %}

app/templates/punjabi.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="row p-5" id="featured" data-aos="fade-down-right">
    <div class="col-md-12 text-center">
        <h2 class="text-uppercase fw-bold"><span class="text-info">Punjabi</span> Books</h2>
        
    </div>
    
    <div class="row p-5">
    {% for pro in object_list %}
        
        <div class="col-md-4">
            <div class="col-md-12 pundiv">
                <div class="text-center">
                    <img src="/media/{{ pro.photo }}"  />
                </div>
                <div class="p-3 bg-dark text-light">
                    <h4>{{ pro.name }}</h4>
                    <div class="d-flex text-danger">
                        <h2 class="pe-4">&#8377;{{ pro.sellingprice }}</h2>
                        <h4 class="text-decoration-line-through ">&#8377; {{ pro.mrp }}</h4>
                    </div>
                    <button class="btn btn-info text-light fw-bold rounded-5">Add to cart</button>
                </div>
            </div>
        </div>
    
    {% endfor %} 

    </div>

</div>

{% endblock %}